# Generated by Django 5.2.3 on 2025-08-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='سؤال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سؤال متداول',
                'verbose_name_plural': 'سؤالات متداول',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
