# Generated by Django 5.2.3 on 2025-08-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='full_name',
            field=models.CharField(blank=True, help_text='برای سوالات ارسالی توسط کاربر', max_length=150, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منتشر شود؟'),
        ),
    ]
