# Generated by Django 5.2 on 2025-07-31 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_number', models.CharField(max_length=100)),
                ('label_email', models.CharField(max_length=100)),
                ('label_address', models.CharField(max_length=100)),
                ('label_social', models.CharField(max_length=100)),
                ('text_number', models.CharField(blank=True, max_length=100, null=True)),
                ('text_email', models.CharField(blank=True, max_length=100, null=True)),
                ('text_address', models.CharField(blank=True, max_length=100, null=True)),
                ('text_social', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='footer.footercategory')),
            ],
        ),
        migrations.AddField(
            model_name='footercategory',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='footer.footersettings'),
        ),
    ]
